#!/bin/bash

echo SPARK_MASTER_HOST= ${SPARK_MASTER_HOST}
echo SPARK_MASTER_PORT= ${SPARK_MASTER_PORT}
echo HDFS_NAMENODE_HOST= ${HDFS_NAMENODE_HOST}
echo HDFS_NAMENODE_PORT= ${HDFS_NAMENODE_PORT}

cd /home
java -jar -Xmx1g FBID-Recomendador-assembly-0.1.0.jar ${SPARK_MASTER_HOST} ${SPARK_MASTER_PORT} ${HDFS_NAMENODE_HOST} ${HDFS_NAMENODE_PORT}